### ISSUE TITLE
More issues with ender chests

### ISSUE THREAD

**Issue by Notme2222** [kyrptonaught/quickshulker#11]
Stacks of ender chests can only be opened through right click in hand, but not with the hotkey. 
Furthermore, you can't do anything with ender chests in enderchests when they are opened with right click or the hotkey. They can't be moved and also can't be taken,

**Comment by kyrptonaught** [comment]
Opening stacks of ender chest through any activation method is working for me, can you verify you're on the most reason version?

**Comment by kyrptonaught** [comment]
I have just released a fix for being unable to move ender chests in opened ender chest
