### ISSUE TITLE
Bug: mouse moves when opening an in-inventory shulker

### ISSUE THREAD

**Issue by Meeni-mc** [kyrptonaught/quickshulker#14]
The mouse cursor gets centered in the screen any time a shulker is opened in inventory. This is very annoying. 

Desired behavior: when opening a shulker in the inventory, the mouse cursor remains at the same place.

**Comment by kyrptonaught** [comment]
This is a tough one I've been having issues with for a while. Problem is vanilla by default resets the cursor to the center when a new screen is opened. I'll have to keep looking for a work around

**Comment by Meeni-mc** [comment]
Could you just save the  cursor position when clicking and restore it after the box opens?

**Comment by kyrptonaught** [comment]
I have fixed this, releasing on curseforge soon
