### ISSUE TITLE
Bug: nametag/anvil rename ignored when opening shulker from inventory

### ISSUE THREAD

**Issue by Meeni-mc** [kyrptonaught/quickshulker#15]
When opening a placed shulker box, the interface that opens contains the name (as modified by nametag/anvil) of the now opened shulker box.

With the mod, the interface contains the generic name, even with renamed shulker boxes. The desired behavior is that the interface contains the name tag of the shulker.

**Comment by kyrptonaught** [comment]
Thanks, I'll investigate

**Comment by kyrptonaught** [comment]
I have fixed this, releasing on curseforge soon

**Comment by Meeni-mc** [comment]
Thanks for fixing this, it is now almost correct: name tags are correctly displayed for renamed shulker boxes.

The default names for non-renamed colored shulker boxes is however not displayed (it should say "Red Shulker Box", instead of "Shulker Box".
