### ISSUE TITLE
Issue with stackable shulker boxes (carpet) and opening a shulker from inventory

### ISSUE THREAD

**Issue by ZuccySuccy** [kyrptonaught/quickshulker#17]
If you have a stack of shulkers (or anything greater than 1 obv) in the top left of your inventory, and a single shulker anywhere else in your inventory, and attempt to place ~however many stacks~ into the shulker and your inventory is either filled with another item manually before closing the inventory or is immediately filled with the another item on the ground, it will replace the stack of shulkers with a singular shulker with the same contents of the filled one 

Reproduction steps:
1: place a stack of shulkers in the top left of your inventory (not required afaik but can help reproduction consistency) with a single shulker next to it 
2: Fill inventory with dummy items (also not required but for simplicity sake) 
3: place a stack of items anywhere in your inventory and drop another stack on the ground (or any other way to immediately fill the empty slot
4: simply place one stack into the shulker and close your inventory 

This obviously isn't an issue with just single stacks, but more so when you are filling multiple shulkers at a time with items sitting on the floor 

https://user-images.githubusercontent.com/74680982/106114180-e7bb8b00-6114-11eb-90b8-3a2d69fb44b0.mp4

**Comment by MeeniMc** [comment]
This is now corrected as well in 1.3.0 :)

**Comment by kyrptonaught** [comment]
Thank you!
