### ISSUE TITLE
Feature request: Crafting Table

### ISSUE THREAD

**Issue by merrx** [kyrptonaught/quickshulker#18]
We all know Ender Chests and Shulker Boxes have the issue to place them down, do your stuff and break them. I really like this mod for solving this issue, good work so far.
But there is an other item which behaves the same: the plain old Crafting Table.
Could the Crafting Table be added as in-inventory openable Item? Like the other two? 
I know there are other mods in the wild, which add an item like Crafting Table on a stick. But this breaks Vanilla-compatibility, which this mod doesn't. It is optional to have it on the client, which is really great.

**Comment by kyrptonaught** [comment]
This was added in 1.1.13
