### ISSUE TITLE
Mod-Compatibility: Allure Crates

### ISSUE THREAD

**Issue by merrx** [kyrptonaught/quickshulker#19]
The Allure mod adds an early game alternative to shulker boxes: Crates.
These behave the same as regular shulkers, but only have 1 row of items to place (9 stacks)
It would be great, if compatibility could be added.

**Comment by kyrptonaught** [comment]
I prefer support to be added by the mods themselves. I would submit a pr, but Allure is closed source, you'll have to contact them
