### ISSUE TITLE
Mod - Compatibility Issue "Servux"

### ISSUE THREAD

**Issue by campbebj** [kyrptonaught/quickshulker#21]
For some reason, when i updated the version of the mod "servux" https://github.com/maruohon/servux on my server part of the behavior of quickshulker stopped working, specifically right clicking on ender chests and shulker boxes in your inventory to open them, while other parts of the mod continue working fine.
I changed nothing else on my client or server at that time. if i remove servux again then the this started working again. I also opened a bug on servux incase they figure it out. https://github.com/maruohon/servux/issues/1

**Comment by kyrptonaught** [comment]
I believe this was fixed on their end
