### ISSUE TITLE
Crafting bench is broken as of 1.1.14

### ISSUE THREAD

**Issue by ghost** [kyrptonaught/quickshulker#23]
Unable to craft anything when opening the crafting bench through quickshulker (valid recipes simply do not result in an item being shown in the output slot). Moreover, items left in crafting slots are lost when closing the crafting bench.

Secondly, right click and keybind behavior is inconsistent for ender chests and crafting benches: right clicking (or using the keybind) on a stack of 2 or more ender chests brings up the ender chest UI, however right clicking (or using the keybind) on a stack of 2 or more crafting benches results in the vanilla behavior of picking up half the stack. Crafting bench UI does open for me when right clicking (or using the keybind) on a single crafting bench.

I am running 1.1.14 on both server and client, ender chest and shulker boxes work as intended. Using fabric loader 0.11.1 with fabric api 0.30.3, on minecraft 1.16.5. Server and client are identical configurations.

**Comment by kyrptonaught** [comment]
This has been fixed in 1.1.15
