### ISSUE TITLE
Ender chest destroyed when doing enderchest-ception

### ISSUE THREAD

**Issue by MeeniMc** [kyrptonaught/quickshulker#26]
I (by mistake) opened an ender-chest that was stored in an ender chest. This deleted the in-inventory ender-chest. 

### Replication steps: 

0. Run 1.1.15+1.17 on both server and client (didn't check if it also happen in singleplayer)
1. Have two ender chests in inventory
2. Click to open one ender chest with QuickShulker
3. Move the second ender chest in the opened ender chest
4. Click the second ender chest to open it with QuickShulker (without first closing the currently opened ender chest) 
5. The inventory window closes suddenly
6. Reopen inventory, the inventory chest is deleted (it doesn't come back with disconnect/reconnect, so it's not just a ghost).
7. Using another on-floor ender-chest, you can verify that the ender-chest in the ender-chest is still present.

**Comment by MeeniMc** [comment]
Ok, I have a more reproducible reproduction steps: 

1. Open an ender-chest in-inventory by right clicking it
2. Left click the (same) ender chest.
3. The ender chest interface flashes and closes, and the ender chest pile is destroyed.

Note that in step 2, if you left click another ender-chest pile, as when moving an ender-chest into an ender-chest, there is no issue.

**Comment by kyrptonaught** [comment]
This has been fixed in 1.1.15
