### ISSUE TITLE
1.17 Server Crashes when Right Clicking a Crafting Table.

### ISSUE THREAD

**Issue by Darkstar77** [kyrptonaught/quickshulker#29]
Installed latest released version from July 19th, server crash occurs when right clicking on a crafting table. Crash report is attached.

[crash-2021-07-19_10.31.50-server.txt](https://github.com/kyrptonaught/quickshulker/files/6841783/crash-2021-07-19_10.31.50-server.txt)

**Comment by kyrptonaught** [comment]
Darn borked again, i submitted 1.1.17 with a fix.
