### ISSUE TITLE
Crashes upon right-clicking destroy button in creative inventory

### ISSUE THREAD

**Issue by cootshk** [kyrptonaught/quickshulker#35]
[Crash report](https://gist.githubusercontent.com/natanfudge/5eed92177999a422c564bc53a4f2e845/raw/7b5aa431fc2d0178478ed91475a1f25fbf3b7ccf/crash.txt)
How to replicate: 
1. go into creative mode
2. grab 2 of an item (I used an anvil)
3. open the survival inventory tap
4. double-right click 'destory item'

**Comment by kyrptonaught** [comment]
This was fixed in 1.2.3
