### ISSUE TITLE
[feature] close when right clicking the opened shulker

### ISSUE THREAD

**Issue by MeeniMc** [kyrptonaught/quickshulker#37]
Idea is to enable closing the shulker that is currently opened by right clicking it in the inventory (if this mode is active in the config, obviously). 

A typical inventory workflow is like this
1. right click a shulker, put stuff in it
2. right click another shulker, that closes the currently opened shulker and opens the new one (great!) put stuff in it
3. return to inventory (e.g., to craft something); this is currently not possible directly (esc, then e); proposal is to let right click return to the prior interface (e.g., opened crafting table, furnace, etc).

**Comment by kyrptonaught** [comment]
I have partially implemented this in 1.2.4. Right clicking the currently opened shulker will just return you to your player inventory. Tracking of the last opened screen is not something that the mod does, and would be rather complicated to implement.
