### ISSUE TITLE
[Feature Request] Add settings to toggle players being able to open certain inventories

### ISSUE THREAD

**Issue by elhertz** [kyrptonaught/quickshulker#40]
I think that opening enderchest and crafting tables breaks mods like "Crafting Pad" and "Ring of the Enderchest" kinda stuff.
That's just my opinion and there's people that don't think and feel like me about this matter so I would really appreciate if you can give us the choice in the form of toggleable settings.
Thank you!

**Comment by kyrptonaught** [comment]
This has been implemented in 1.2.5

**Comment by elhertz** [comment]
Wow that was really fast!
Could you also add a setting to toggle the enderchest? That would be perfection, thanks!
