### ISSUE TITLE
Disabling "quickEChest" doesn't disable enderchests from the "Upgraded Ender Chests" mod

### ISSUE THREAD

**Issue by elhertz** [kyrptonaught/quickshulker#43]
Title self-explanatory.
[Upgraded Ender Chests](https://www.curseforge.com/minecraft/mc-mods/upgraded-ender-chests)

**Comment by kyrptonaught** [comment]
Ah, this will have to be done in an update to Upgraded E chests. I'll get this done soon

**Comment by kyrptonaught** [comment]
An update to upgrade e chests has been released
