### ISSUE TITLE
Right Clicking on a slot while holding a stack of Ender Chests places an item like a bundle

### ISSUE THREAD

**Issue by Decrepitdoors** [kyrptonaught/quickshulker#44]
I have the mod installed on my server and client, the same jar file.

I just updated to 1.3.0 and tried to open my ender_chest from the stack I keep in my inventory and ended up taking a shulker_box out, I then tried to place an ender chest in another slot to see if that would fix it but it just put a shulker_box in that slot from the ender_chest. 
I ended up putting the rest of the ender_chests into my ender_chest which works as a work around. but now I have 2 slot in my inventory taken up by the ender_chests

**Comment by kyrptonaught** [comment]
Quickshulker 1.3.0 was changed to require the quick stack to be a single item. This helps with bugs and dupes. This was also done to help with consistently of the newly implemented bundling functionality. Allowing bundling actions to function on stacks may interfere with the normal vanilla right click functionality(Stack splitting).

It does seem though that bundling does ignore the check for stacks. I will release a fix for this shortly

**Comment by kyrptonaught** [comment]
1.3.2 now removed the check for single stacks in ender chests(and crafting tables/stonecutters). You can now open them, and bundle items into them if stacked

**Comment by MeeniMc** [comment]
This change makes it impossible to right click a stack of enderchests to split it in two. How is the player supposed to interact with the stack to divide it now?

**Comment by Decrepitdoors** [comment]
I agree with MeeniMc the bundle actions should only happen when the item is a single item, no stacks, as it stops players being able to use items as expected. This just adds functionality to single item stacks.

My original report wasn't worded very well.

**Comment by kyrptonaught** [comment]
I think what MeeniMc is talking about isn't related to bundles, but rather just right clicking the stack with an empty hand to pick up half of it. The only bundle option that is enabled in stacks is holding an item and right click inserting it into the enderchest

I think that bundleing operation is okay to use with stacks. But right clicking on a stack with an empty hand should split it, rather than trigger the open
