### ISSUE TITLE
Feature quick shulker hot key can return to the previous inventory 

### ISSUE THREAD

**Issue by opsaaaaa** [kyrptonaught/quickshulker#49]
I just discoved the hot key feature for navigating boxes in the inventory. Totally awesome. 

Suggestion, Using the quick shulker hot key while in a shulker box and not hovering over a another box should return to the previous inventory. 

Given that i opened a crafting table, 
And I click k over my craft resources box, 
And I move some items to my inventory 
When hit k without hovering over a box.
Then i want to return to the crafting table.

you can basically do this by opening a crafting table item with k, but that take up a slot.

**Comment by kyrptonaught** [comment]
This was partially added. There is a config option for "Right Click Close". Enabling this will allow you to close the opened shulker box by reactivating it.
