### ISSUE TITLE
Allows item duplication

### ISSUE THREAD

**Issue by aakova** [kyrptonaught/quickshulker#5]
Add item to shulker, place shulker in hot-bar;
Right click to open shulker;
Left click and move shulker to inventory, note that the shulker inventory is still open;
Remove item from shulker
Right click to open shulker;
Remove item from shulker.

**Comment by kyrptonaught** [comment]
Interesting, I suppose a fix would be to just make the opened shulker box immovable

**Comment by kyrptonaught** [comment]
Fixed in 1.1.4
