### ISSUE TITLE
right clicking a shulker / ender chest makes the player right click in the world

### ISSUE THREAD

**Issue by subatomic-olive** [kyrptonaught/quickshulker#50]
eg. if I hold a shield in offhand and open a shulker box, the shield is used while the shulker box is open

(1.18.1, v1.3.3)

**Comment by Vigilans** [comment]
Same, it has been working for a long time until last one or two weeks. Then even if I removed all mods except fabric api, along with the `.fabric` and `configs` folder, or even create a new game with oldest acceptable version of minecraft 1.18 and fabric (loader 12.5 + api 0.43.1), the problem still exists.

**Comment by MeeniMc** [comment]
I think it's another form of #16
