### ISSUE TITLE
Maven import fails

### ISSUE THREAD

**Issue by i509VCB** [kyrptonaught/quickshulker#6]
So I was updating Bulky Shulkies and I noticed that I get an error saying `kryptconfig` does not exist causing import to fail:
https://gist.github.com/i509VCB/3b6133891381514241644890ddf5a99b

**Comment by kyrptonaught** [comment]
For whatever reason it’s not searching on the right bintray repo for the lib: https://dl.bintray.com/kyrptonaught/kyrptconfig

You can add this manually until I have the time to take a look

**Comment by kyrptonaught** [comment]
I've pushed a new version of quickshulker to the repo, can you try 1.1.3-20w18a  and see if it works?

**Comment by i509VCB** [comment]
I'll check in a few hours

**Comment by i509VCB** [comment]
Seems like I just have to include the `kryptconfig` maven in order for it to work.

**Comment by kyrptonaught** [comment]
That’s very odd, not sure why that’s happening
