### ISSUE TITLE
Update Minecraft version tags for CurseForge

### ISSUE THREAD

**Issue by ghost** [kyrptonaught/quickshulker#62]
Add the tag for Minecraft versions 1.19.1 and 1.19.2 for the [quickshulker-1.3.9-1.19.jar](https://www.curseforge.com/minecraft/mc-mods/quick-shulker/files/4008788) so its possible/easier to use it in modpacks. The mod works without problems in these versions as I tested.

**Comment by kyrptonaught** [comment]
Done, thanks!
