### ISSUE TITLE
Can't open boxes under water

### ISSUE THREAD

**Issue by MeeniMc** [kyrptonaught/quickshulker#63]
Since the fix for a dupe bug introduced that one cannot open an in-inventory box when aiming at a non-air block, it has become impossible to open a shulker under water. 

Ideally, it would be better if opening in-inventory would work again even when aiming at placeable blocks, but in the meantime, refining the test to include water to the list of 'valid' aims would be a good step.

**Comment by MeeniMc** [comment]
Problem is more generally that boxes cannot be opened when having a target block.

**Comment by MICOAST** [comment]
hope for v1.4.1 in 1.19.3.Thanks.When it runs in 1.19.3,cause serious bug, #78
