### ISSUE TITLE
Recent change that prevent quick-shulkering when targeting a block is crippling

### ISSUE THREAD

**Issue by MeeniMc** [kyrptonaught/quickshulker#71]
In this commit, quick shulkering when targeting a block has been disabled
https://github.com/kyrptonaught/quickshulker/commit/56c2929996c2b315adb29bf1da4c733f681f982b#commitcomment-112197960; As I understand this is to prevent a duping scenario. 

Given that
1. This renders using the mod extremely tedious, borderline broken/unusable.
2. There seems to exist at least 2 or 3 other dupe scenarios that are still unpatched, thus reducing the emergency of fixing this particular vector with all emergency.

I propose that this change is reverted until a better fix is found, or -at least- it is the last dupe standing.

**Comment by MeeniMc** [comment]
Related to #63 (as the new underwater behavior is also caused by this same commit)

**Comment by Steve-Brule** [comment]
Completely agree. At the very least you should get an error or popup of some kind to inform you why the mod isn't working. I restarted the server and client multiple times before I realized what was happening.

This should totally be an optional mitigation, I am not concerned about cheating on my server and would absolutely disable this if I could.

**Comment by MeeniMc** [comment]
https://github.com/MeeniMc/quickshulker/releases @Steve-Brule
