### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by jitui-star** [kyrptonaught/quickshulker#73]
1.20 please

**Comment by MeeniMc** [comment]
1.19.4 version -almost- work on 1.20., except that the game may crash when picking items out of quick-opened shulkers.

**Comment by jitui-star** [comment]
Thanks,i'll try it

**Comment by jitui-star** [comment]
The game does crash when I open it. Can you fix this issue?

**Comment by kyrptonaught** [comment]
Out now
